name: {{cookiecutter.project_slug}} Automation

on:
  push:
  schedule:
    - cron: "0 6 * * 1"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create Docker Mounted Content
      run: |
        echo | ssh-keygen
        touch ${HOME}/.gitconfig
        touch ${HOME}/.gitconfig_global
    - name: Ensure File System is Writable by the Container
      run: |
        sudo chmod -R 777 .
    - name: Build Container
      run: |
        docker-compose build
        docker-compose up -d
    - name: Run Linter
      run: |
        docker-compose exec -T {{cookiecutter.project_slug}} bash -l -c 'scripts/commander.sh lint-validate'
    - name: Run Sec Test
      run: |
        docker-compose exec -T {{cookiecutter.project_slug}} bash -l -c 'scripts/commander.sh sectest'
    - name: Run Unit Tests
      run: |
        docker-compose exec -T {{cookiecutter.project_slug}} bash -l -c 'scripts/commander.sh test coverage'
      - name: Report Job Status
        if: always()
        run: |
          if [[ $status == "failure" ]]; then curl -X POST -H 'Content-type: application/json' --data '{"text":"{{cookiecutter.project_slug}}: build has failed!"}' "${WEBHOOK_URL}"; fi
        env:
{% raw %}
          status: ${{job.status}}
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
{% endraw %}