name: Python In A Box Self Test
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
      with:
        path: 'template'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Requirements
      run: |
        pip install cookiecutter
    - name: Create Template
      run: |
        git config --global user.email "somedude@coolstartup.com"
        git config --global user.name "Pro Buddy Dev"
        echo -e '\n\n\nfalse\nfalse\nfalse\n' | cookiecutter template/
    - name: Ensure File System is Writable by the Container
      run: |
        chmod -R 777 mmmm_cookies
    - name: Build Docker Image, Start Container
      run: |
        cd mmmm_cookies
        docker-compose build
        docker-compose up -d
        sleep 1
    - name: Test the Lint Command
      run: |
        cd mmmm_cookies
        docker-compose exec -T mmmm_cookies bash -l -c './scripts/commander.sh lint'
    - name: Test the Lint-Validate Command
      run: |
        cd mmmm_cookies
        docker-compose exec -T mmmm_cookies bash -l -c './scripts/commander.sh lint-validate'
    - name: Test the Reinstall Requirements Command
      run: |
        cd mmmm_cookies
        docker-compose exec -T mmmm_cookies bash -l -c './scripts/commander.sh reinstall-requirements'
    - name: Test the Sectest Command
      run: |
        cd mmmm_cookies
        docker-compose exec -T mmmm_cookies bash -l -c './scripts/commander.sh sectest'
    - name: Test the Setup Commands
      run: |
        cd mmmm_cookies
        docker-compose exec -T mmmm_cookies bash -l -c './scripts/commander.sh setup'
    - name: Test the Test Command
      run: |
        cd mmmm_cookies
        docker-compose exec -T mmmm_cookies bash -l -c './scripts/commander.sh test'
    - name: Test the Test-Coverage Command
      run: |
        cd mmmm_cookies
        docker-compose exec -T mmmm_cookies bash -l -c './scripts/commander.sh test-coverage'
    - name: Test Priviledge Escalation
      run: |
        cd mmmm_cookies
        docker-compose exec -T mmmm_cookies bash -l -c 'sudo ls -la /root'
    - name: Test CLI Update
      run: |
        cd mmmm_cookies
        docker-compose exec -T mmmm_cookies bash -l -c './scripts/commander.sh update && [[ -f ./scripts/common/.archive/common.sh ]] && [[ -f ./development/bash/.archive/.bashrc ]] && [[ -f ./scripts/common/common.sh ]] && [[ -f ./development/bash/.archive/.bashrc ]] && ./scripts/commander.sh'
